### PR TITLE
require soundfile, not pysoundfile

### PR DESCRIPTION
**Pull request by nwh**
pysoundfile is deprecated: https://github.com/bastibe/PySoundFile

#### What does this implement/fix? Explain your changes.

The PySoundFile page on GitHub indicates that PySoundFile was renamed to SoundFile.

The install command is now `pip install soundfile`.

#### Any other comments?

I had to comment out the pytest lines in `setup.cfg` in order to run the tests.  But, the tests did pass!

Running pytest with `setup.cfg` as is results in:

```
↪ pytest
================================================================================ test session starts ================================================================================
platform darwin -- Python 3.6.12, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /Users/nw_henderson/github.com/nwh/pyrubberband, configfile: setup.cfg
plugins: cov-2.10.1, pep8-1.0.6
collected 0 items / 1 error                                                                                                                                                         
Coverage.py warning: No data was collected. (no-data-collected)

====================================================================================== ERRORS =======================================================================================
___________________________________________________________________________ ERROR collecting test session ___________________________________________________________________________
Direct construction of Pep8Item has been deprecated, please use Pep8Item.from_parent.
See https://docs.pytest.org/en/stable/deprecations.html#node-construction-changed-to-node-from-parent for more details.

---------- coverage: platform darwin, python 3.6.12-final-0 ----------
Name                       Stmts   Miss  Cover   Missing
--------------------------------------------------------
pyrubberband/__init__.py       3      3     0%   4-7
pyrubberband/pyrb.py          72     72     0%   3-257
pyrubberband/version.py        1      1     0%   4
--------------------------------------------------------
TOTAL                         76     76     0%

============================================================================== short test summary info ==============================================================================
ERROR 
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================================================= 1 error in 0.09s ==================================================================================
```

### CODE REVIEW

**Comment by bmcfee** [comment]
Thanks for this.

> I had to comment out the pytest lines in `setup.cfg` in order to run the tests. But, the tests did pass!

If there's a problem with the tests, we need to fix that before merging.  I'm not sure when I'll have time to has that out, but in the meantime, it's up for grabs if anyone wants to take a shot at it!

**Comment by nwh** [comment]
> If there's a problem with the tests, we need to fix that before merging. I'm not sure when I'll have time to has that out, but in the meantime, it's up for grabs if anyone wants to take a shot at it!

I'll take a crack at it.

**Comment by nwh** [comment]
The issue appears to come from the `--pep8` flag.  Here is what I see with the  pytest config completely on the command line:

```
$ pytest --ignore docs/conf.py --cov-report term-missing --cov pyrubberband --pep8
================================================ test session starts ================================================
platform darwin -- Python 3.6.12, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /Users/nw_henderson/github.com/nwh/pyrubberband
plugins: cov-2.10.1, pep8-1.0.6
collected 0 items / 1 error                                                                                         
Coverage.py warning: No data was collected. (no-data-collected)

====================================================== ERRORS =======================================================
___________________________________________ ERROR collecting test session ___________________________________________
Direct construction of Pep8Item has been deprecated, please use Pep8Item.from_parent.
See https://docs.pytest.org/en/stable/deprecations.html#node-construction-changed-to-node-from-parent for more details.

---------- coverage: platform darwin, python 3.6.12-final-0 ----------
Name                       Stmts   Miss  Cover   Missing
--------------------------------------------------------
pyrubberband/__init__.py       3      3     0%   4-7
pyrubberband/pyrb.py          72     72     0%   3-257
pyrubberband/version.py        1      1     0%   4
--------------------------------------------------------
TOTAL                         76     76     0%

============================================== short test summary info ==============================================
ERROR 
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================= 1 error in 0.08s ==================================================
$ pytest --ignore docs/conf.py --cov-report term-missing --cov pyrubberband
================================================ test session starts ================================================
platform darwin -- Python 3.6.12, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /Users/nw_henderson/github.com/nwh/pyrubberband
plugins: cov-2.10.1, pep8-1.0.6
collected 294 items                                                                                                 

tests/test_pyrb.py .......................................................................................... [ 30%]
............................................................................................................. [ 67%]
...............................................................................................               [100%]

---------- coverage: platform darwin, python 3.6.12-final-0 ----------
Name                       Stmts   Miss  Cover   Missing
--------------------------------------------------------
pyrubberband/__init__.py       3      0   100%
pyrubberband/pyrb.py          72      1    99%   27
pyrubberband/version.py        1      0   100%
--------------------------------------------------------
TOTAL                         76      1    99%


================================================ 294 passed in 6.33s ================================================
```

[pytest-pep8](https://pypi.org/project/pytest-pep8/#history) has not been updated since 2014.  Seems like it doesn't work with current version of `pytest`.

I just pushed a commit that removes `pytest-pep8` and the `--pep8` flag. Also added `numpy` to install requirements.

**Comment by nwh** [comment]
Also -- tests passed for me in both python 3.6 and 3.9.  I did not check the versions between.

**Review by bmcfee — APPROVED** [review]
LGTM!  Thanks!

**Pull request merged**
